services:
  - type: web
    name: urbanmood
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application -k gthread --threads 4 --timeout 60 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MAILERSEND_API_KEY
        sync: false
